### ISSUE TITLE
IPDFMacSecureTextField and floating "Password..." button

### ISSUE THREAD

**Issue by marcocattai** [mmackh/Catalyst-Helpers#2]
is there any way to remove the floating "Password..." button on MAC Catalyst? . It appears when the Password TextField has the focus and it prevent from intercepting the RETURN Key, in the textfield, From the keyboard

<img width="372" alt="Screenshot 2019-11-21 at 16 09 40" src="https://user-images.githubusercontent.com/436669/69355213-541d3d80-0c79-11ea-8869-7d14676b8f73.png">

**Comment by mmackh** [comment]
Hi, please use the `secureTextEntryWithoutAutofill` and not `secureTextEntry`
