### ISSUE TITLE
IPDFMacSecureTextField - Text Centered + Selection

### ISSUE THREAD

**Issue by marcocattai** [mmackh/Catalyst-Helpers#3]
Try to center the attributed Text and then try to Select it all with CMD+A - The selection is not centered.
<img width="279" alt="Screenshot 2019-11-22 at 10 09 27" src="https://user-images.githubusercontent.com/436669/69417268-3e0e8c00-0d10-11ea-868e-01f5c9590dca.png">

**Comment by mmackh** [comment]
Yeah, out of the scope of this control (very basic, left aligned use in my app). Pull requests to fix this issue are welcome.
