### ISSUE TITLE
Note on blue highlights in UITableViewCell on selection

### ISSUE THREAD

**Issue by malhal** [mmackh/Catalyst-Helpers#4]
I think the Finder likely resigns the first responder on selection which is why it doesn't highlight blue, i.e. so arrow key commands go to the file list not the sidebar list. Whereas the catalyst sidebar tableview becomes the first responder on selection thus goes blue. So the solution is to make the detail view controller or its view become the first responder and the table cell should stay grey on every click.

In this WWDC video he says we have to look after our responder chain in catalyst:
https://developer.apple.com/videos/play/wwdc2019/235/?time=140

**Comment by mmackh** [comment]
Hi Malcom, 

thanks for bringing this up - I did indeed look at the responder chain first, coming from an AppKit background. Assigning the tableView (for example) as a new responder works, but only in a limited fashion. There will be a short blue flash, which looks like a UI glitch. I didn't like that behaviour, so I found a workaround.

**Comment by malhal** [comment]
Subclassing the master UITableView and returning NO from canBecomeFirstResponder prevents that flash (and keyboard navigation still works).

I also noticed in News its always blue, but in Podcasts its always grey. Then in Photos if you click Photos in the sidebar its grey but if you press tab twice it goes blue!
